apiVersion: v1
kind: Service
metadata:
  labels:
    serving.knative.dev/route: serverless-quarkus-sb-demo-app
  name: serverless-quarkus-sb-demo
  namespace: knative-test
  ownerReferences:
  - apiVersion: serving.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Route
    name: serverless-app
  resourceVersion: "1198258"
spec:
  externalName: kourier-internal.knative-serving-ingress.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}

