apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-sb-demo
spec:
  template:
    metadata:
      annotations:
      labels:
    spec:
      containerConcurrency: 0
      containers:
        - image: 'image-registry.openshift-image-registry.svc:5000/quarkus-sb-demo/quarkus-sb-demo:latest'
          imagePullPolicy: Always
          name: quarkus-sb-demo
          resources:
            requests:
              memory: "50Mi"
              cpu: "75m"
            limits:
              memory: "150Mi"
              cpu: "150m"
          livenessProbe:
            initialDelaySeconds: 1
            httpGet:
              path: /health/live
          readinessProbe:
            initialDelaySeconds: 1
            httpGet:
              path: /health/ready
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100

