apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-sb-demo
spec:
  template:
    metadata:
      annotations:
      labels:
    spec:
      containerConcurrency: 0
      containers:
        - image: 'image-registry.openshift-image-registry.svc:5000/quarkus-sb-demo/quarkus-sb-demo:latest'
          imagePullPolicy: IfNotPresent
          name: quarkus-sb-demo
          ports:
          - containerPort: 8080
          resources: {}
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100



